### ISSUE TITLE
[FEATURE] Logo for Project README 

### ISSUE THREAD

**Issue by Trianglium** [Dixon3991/cardgame#4]
## Description
Create a logo for the project's [README.md](./README.md) to replace the temp [logo](./doc/logo/logo80x40.png).

## Tasks
- [ ] Create a logo and save as a PNG
- [ ] The README template had the logo at 80x80 (px) but the mock logo is at 80x40 (px). Size it however you see fit, but add the dimensions to the filename (IE [./doc/logo/logo80x40.png](./doc/logo/logo80x40.png)).
- [ ] Delete [./doc/logo/logo80x40.png](./doc/logo/logo80x40.png)
- [ ] Upload new logo to [./doc/logo](./doc/logo)
- [ ] Update the logo's `src` , `width`, and `height` in [README.md](./README.md). The project logo is in the `<!-- PROJECT LOGO -->`  section: 
```html
<!-- PROJECT LOGO -->
<br />
<div align="center">
  <a href="https://github.com/Dixon3991/cardgame">
    <img src="doc/logo/logo80x40.png" alt="Logo" width="80" height="40">
  </a>
```
